# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               What She Said
tagline:             'life is a joke'
description:         'a frivolous exploration of life, the universe, and everything'
url:                 http://whatshesaid.bumnetworks.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Yvette Zhukovsky
  url:               http://whatshesaid.bumnetworks.com
  email:             yzhukovs@bumnetworks.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
